add symfony/options-resolver ^6.0
kriswallsmith/Buzz pull request #424
Opened 2022-02-10 23:46 UTC by Jimbolino

2022-02-15 04:22 UTC, ZebulanStanphill requested changes

2022-02-15 04:22 UTC, ZebulanStanphill commented on composer.json
> +        "symfony/options-resolver": "^3.4 || ^4.0 || ^5.0" || ^6.0",
There's a breaking typo here. Here's the fix.
```suggestion
        "symfony/options-resolver": "^3.4 || ^4.0 || ^5.0 || ^6.0",
```

2022-02-15 04:23 UTC, ZebulanStanphill commented
In case anyone is worried about breaking changes: the only listed change for version 6.0 is the [removal of `OptionsResolverIntrospector::getDeprecationMessage()`](https://github.com/symfony/options-resolver/blob/6.0/CHANGELOG.md#60), which is [not used by this project](https://github.com/kriswallsmith/Buzz/search?q=getDeprecationMessage), so `composer.json` is indeed the only thing that needs to be changed.

2022-03-25 13:55 UTC, merged

2022-03-25 13:55 UTC, Nyholm commented
Thank you

2022-03-25 13:57 UTC, Nyholm commented
https://github.com/kriswallsmith/Buzz/releases/tag/1.2.1